### ISSUE TITLE
Cannot share layers across application

### ISSUE THREAD

**Issue by computerwizjared** [aws/aws-sam-cli#1698]
### Description

I am trying to use SAM to build an application with multiple sub-applications inside of it, along with some shared layers across the whole application and multiple sub-applications. However, it doesn't appear that I can have the parent application template build a layer and pass it into a child template when testing locally with `sam local start-api`.

### Steps to reproduce

Create a parent application with this template.yaml:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test SAM Project

Resources:
  SubApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: projects/subapplication/template.yaml
      Parameters:
        TestLayerId: !Ref TestLayer
  TestLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Test layer for passing to sub-application
      ContentUri: layers/test
      CompatibleRuntimes:
        - nodejs10.x
        - nodejs12.x
```
and for the sub-application, this template.yaml:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test SAM Sub-Application
  
Parameters:
  TestLayerId:
    Type: String
    Description: ID of Test Lambda Layer

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/test
      Handler: test.handler
      Runtime: nodejs10.x
      Layers:
        - !Ref TestLayerId
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: /test
            Method: GET
```

### Observed result

```
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
local start-api command is called
Collected default values for parameters: {}
2 resources found in the template
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local start-api', 'duration': 1103, 'exitReason': 'InvalidLayerVersionArn', 'exitCode': 1, 'requestId': '13fd6941-43c6-4e57-a679-9d251168fa7d', 'installationId': '17586f41-9a7d-4535-97de-f7dc2b3e0b07', 'sessionId': 'cf592c6d-9552-49b0-82a7-c015d56a6abd', 'executionEnvironment': 'CLI', 'pyversion': '3.6.7', 'samcliVersion': '0.39.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: TestLayerId is an Invalid Layer Arn.
```

### Expected result

I expect the Layer from the parent template to be built and passed into the sub-application template.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 1909 (18363)
2. `sam --version`: 0.39.0

**Comment by heitorlessa** [comment]
I am having the same issue though I was using a SSM Parameter to store Layer ARN.

**It seems that this issue can be reproduced if there is any `AWS::Serverless::Application` resource in the same template you reference a Layer using `!Ref`.** I've tried injecting a Layer ARN via SSM Parameter in another template that doesn't have an `AWS::Serverless::Application` resource and it works just fine.

**Workaround**:  Replacing **`sam deploy` to `aws cloudformation deploy`** does the trick for me since sam deploy is mostly a wrapper -- Any ideas @sriram-mv?

Perhaps the tag isn't appropriate as this isn't a feature but an issue.

**Comment by heitorlessa** [comment]
I take it back - just did a fresh deployment and got hit by this when using SSM Parameter. **The issue comes from this [function in SAM CLI](https://github.com/awslabs/aws-sam-cli/blob/39add9acd0c7532129a6543134919eb6ae9df4f3/samcli/lib/providers/provider.py#L132)** - @sriram-mv 

Issue here is that the OP and myself are passing a reference that will only be resolved in CloudFormation, therefore the value SAM CLI is parsing is not resolved, and that's why changing from `sam deploy` to `aws cloudformation deploy` works --- Below is an excerpt of the template from my service that reproduces the issue.

---

**Template**

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: Environment stage or git branch
    Default: develop

  SharedLibsLayer:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Project shared libraries Lambda Layer ARN
    Default: /develop/shared/lambda/layers/projectArn

Globals:
  Function:
    Timeout: 10
    Tracing: Active
    MemorySize: 512
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: payment
        POWERTOOLS_METRICS_NAMESPACE: ServerlessAirline
        LOG_LEVEL: INFO

Resources:
  CollectPayment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ServerlessAirline-CollectPayment-${Stage}
      Handler: collect.lambda_handler
      Runtime: python3.7
      CodeUri: src/collect-payment
      Layers:
        - !Ref SharedLibsLayer
```

**Comment by aahung** [comment]
> I expect the Layer from the parent template to be built and passed into the sub-application template.

v1.20.0 released nested stack support and parameters can now passed to child stacks when using `local start-api`, please re-open if it does not solve your problem.
