### ISSUE TITLE
sam build Fails with ConnectionResetError 104

### ISSUE THREAD

**Issue by RockManJoe64** [aws/aws-sam-cli#2906]
### Description

When executing the command `sam build -t serverless.template` I am getting several errors depending on the environment.

#### PowerShell
1. Create an AWS Lambda project using the Visual Studio 2019 AWS Toolkit for Visual Studio extension.
2. Open a PowerShell terminal in Admin mode
2. Execute the command `sam build -t serverless.template --debug`

### Observed result:
Output freezes after the last line:
```
2021-05-25 23:22:51,927 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-05-25 23:22:52,094 | 'build' command is called
2021-05-25 23:22:52,095 | No Parameters detected in the template
2021-05-25 23:22:52,115 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:22:52,116 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:22:52,116 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:22:52,116 | 4 resources found in the template
2021-05-25 23:22:52,117 | Found Serverless function with name='Get' and ImageUri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy'
2021-05-25 23:22:52,117 | Found Serverless function with name='GetOrders' and ImageUri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy'
2021-05-25 23:22:52,117 | Found Serverless function with name='CreateOrder' and ImageUri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy'
2021-05-25 23:22:52,117 | No Parameters detected in the template
2021-05-25 23:22:52,133 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:22:52,135 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:22:52,135 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:22:52,137 | Instantiating build definitions
2021-05-25 23:22:52,150 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(None, ., Image, , ef42f946-0b9e-4e79-aa91-4cc47c80ff27, {'Dockerfile': 'Dockerfile', 'DockerContext': '.', 'DockerTag': ''}, []), Function: Function(name='Get', functionname='Get', runtime=None, memory=256, timeout=30, handler=None, imageuri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy', packagetype='Image', imageconfig={'EntryPoint': ['/lambda-entrypoint.sh'], 'Command': ['ExampleAwsProject::Lambdas.Functions::Get']}, codeuri='.', environment=None, rolearn=None, layers=[], events={'RootGet': {'Type': 'Api', 'Properties': {'Path': '/', 'Method': 'GET', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'Dockerfile': 'Dockerfile', 'DockerContext': '.', 'DockerTag': ''}, codesign_config_arn=None))
2021-05-25 23:22:52,151 | Same function build definition found, adding function (Previous: BuildDefinition(None, ., Image, , ef42f946-0b9e-4e79-aa91-4cc47c80ff27, {'Dockerfile': 'Dockerfile', 'DockerContext': '.', 'DockerTag': ''}, ['Get']), Current: BuildDefinition(None, ., Image, , 8a11947a-b664-4269-af71-c4e5346b4644, {'Dockerfile': 'Dockerfile', 'DockerContext': '.', 'DockerTag': ''}, []), Function: Function(name='GetOrders', functionname='GetOrders', runtime=None, memory=256, timeout=30, handler=None, imageuri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy', packagetype='Image', imageconfig={'EntryPoint': ['/lambda-entrypoint.sh'], 'Command': ['ExampleAwsProject::Lambdas.Orders.OrderLambdas::GetOrders']}, codeuri='.', environment=None, rolearn=None, layers=[], events={'RootGet': {'Type': 'Api', 'Properties': {'Path': '/orders', 'Method': 'GET', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'Dockerfile': 'Dockerfile', 'DockerContext': '.', 'DockerTag': ''}, codesign_config_arn=None))
2021-05-25 23:22:52,152 | Same function build definition found, adding function (Previous: BuildDefinition(None, ., Image, , ef42f946-0b9e-4e79-aa91-4cc47c80ff27, {'Dockerfile': 'Dockerfile', 'DockerContext': '.', 'DockerTag': ''}, ['Get', 'GetOrders']), Current: BuildDefinition(None, ., Image, , 832b49d8-aaac-4ba5-af4b-3c477b25868e, {'Dockerfile': 'Dockerfile', 'DockerContext': '.', 'DockerTag': ''}, []), Function: Function(name='CreateOrder', functionname='CreateOrder', runtime=None, memory=256, timeout=30, handler=None, imageuri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy', packagetype='Image', imageconfig={'EntryPoint': ['/lambda-entrypoint.sh'], 'Command': ['ExampleAwsProject::Lambdas.Orders.OrderLambdas::CreateOrder']}, codeuri='.', environment=None, rolearn=None, layers=[], events={'RootGet': {'Type': 'Api', 'Properties': {'Path': '/orders', 'Method': 'POST', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'Dockerfile': 'Dockerfile', 'DockerContext': '.', 'DockerTag': ''}, codesign_config_arn=None))
2021-05-25 23:22:52,153 | Building codeuri: . runtime: None metadata: {'Dockerfile': 'Dockerfile', 'DockerContext': '.', 'DockerTag': ''} functions: ['Get', 'GetOrders', 'CreateOrder']
2021-05-25 23:22:52,154 | Building to following folder C:\Users\SomeUser\Workspace\ExampleAwsProject\.aws-sam\build\Get
2021-05-25 23:22:52,154 | Building image for Get function
2021-05-25 23:22:52,163 | Setting DockerBuildArgs: {} for Get function
```
#### Git Bash
Executing the same command in Git Bash gives:
```
$ sam build --use-container -t serverless.template --debug
2021-05-25 23:12:21,442 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-05-25 23:12:21,861 | 'build' command is called
2021-05-25 23:12:21,861 | Starting Build inside a container
2021-05-25 23:12:21,862 | Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 419, 'exitReason': 'TemplateNotFoundException', 'exitCode': 1, 'requestId': '0a204169-e7c9-46cf-8bb0-bf1f57104fd2', 'installationId': '1742ae7c-f4b5-43e5-8c7e-4b0d94804823', 'sessionId': 'bb41d959-d2b3-4e33-99b6-236d1a875180', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.15.0'}}]}
2021-05-25 23:12:23,230 | Telemetry response: 200
Error: Template file not found at C:\Program Files\Amazon\AWSSAMCLI\bin\serverless.template
```
#### Ubuntu on WSL2
Executing the same command in WSL2 Ubuntu gives:
```
$ sam build --use-container -t serverless.template --debug
2021-05-25 23:06:00,021 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-05-25 23:06:00,022 | Using config file: samconfig.toml, config environment: default
2021-05-25 23:06:00,022 | Expand command line arguments to:
2021-05-25 23:06:00,022 | --template_file=/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject/serverless.template --use_container --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache
2021-05-25 23:06:00,055 | 'build' command is called
2021-05-25 23:06:00,055 | Starting Build inside a container
2021-05-25 23:06:00,059 | No Parameters detected in the template
2021-05-25 23:06:00,080 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:06:00,080 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:06:00,083 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:06:00,084 | 4 stacks found in the template
2021-05-25 23:06:00,084 | No Parameters detected in the template
2021-05-25 23:06:00,105 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:06:00,105 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:06:00,105 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:06:00,105 | 4 resources found in the stack
2021-05-25 23:06:00,106 | No Parameters detected in the template
2021-05-25 23:06:00,125 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:06:00,126 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:06:00,126 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:06:00,126 | Found Serverless function with name='Get' and ImageUri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy'
2021-05-25 23:06:00,126 | --base-dir is not presented, adjusting uri . relative to /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject/serverless.template
2021-05-25 23:06:00,127 | --base-dir is not presented, adjusting uri . relative to /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject/serverless.template
2021-05-25 23:06:00,128 | Found Serverless function with name='GetOrders' and ImageUri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy'
2021-05-25 23:06:00,129 | --base-dir is not presented, adjusting uri . relative to /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject/serverless.template
2021-05-25 23:06:00,129 | --base-dir is not presented, adjusting uri . relative to /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject/serverless.template
2021-05-25 23:06:00,130 | Found Serverless function with name='CreateOrder' and ImageUri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy'
2021-05-25 23:06:00,130 | --base-dir is not presented, adjusting uri . relative to /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject/serverless.template
2021-05-25 23:06:00,131 | --base-dir is not presented, adjusting uri . relative to /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject/serverless.template
2021-05-25 23:06:00,132 | No Parameters detected in the template
2021-05-25 23:06:00,152 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:06:00,153 | Unable to resolve property Role: None. Leaving as is. 
2021-05-25 23:06:00,153 | Unable to resolve property Role: None. Leaving as is.
2021-05-25 23:06:00,162 | Instantiating build definitions
2021-05-25 23:06:00,166 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(None, /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject, Image, , e326089c-024b-410c-9fe4-d208b1288155, {'Dockerfile': 'Dockerfile', 'DockerContext': '/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', 'DockerTag': ''}, {}, []), Function: Function(name='Get', functionname='Get', runtime=None, memory=256, timeout=30, handler=None, imageuri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy', packagetype='Image', imageconfig={'EntryPoint': ['/lambda-entrypoint.sh'], 'Command': ['ExampleAwsProject::Lambdas.Functions::Get']}, codeuri='/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', environment=None, rolearn=None, layers=[], events={'RootGet': {'Type': 'Api', 'Properties': {'Path': '/', 'Method': 'GET', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'Dockerfile': 'Dockerfile', 'DockerContext': '/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', 'DockerTag': ''}, inlinecode=None, codesign_config_arn=None, stack_path=''))
2021-05-25 23:06:00,166 | Same function build definition found, adding function (Previous: BuildDefinition(None, /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject, Image, , e326089c-024b-410c-9fe4-d208b1288155, {'Dockerfile': 'Dockerfile', 'DockerContext': '/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', 'DockerTag': ''}, {}, ['Get']), Current: BuildDefinition(None, /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject, Image, , 354889e7-225f-4bfe-b342-5772b7dd9211, {'Dockerfile': 'Dockerfile', 'DockerContext': '/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', 'DockerTag': ''}, {}, []), Function: Function(name='GetOrders', functionname='GetOrders', runtime=None, memory=256, timeout=30, handler=None, imageuri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy', packagetype='Image', imageconfig={'EntryPoint': ['/lambda-entrypoint.sh'], 'Command': ['ExampleAwsProject::Lambdas.Orders.OrderLambdas::GetOrders']}, codeuri='/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', environment=None, rolearn=None, layers=[], events={'RootGet': {'Type': 'Api', 'Properties': {'Path': '/orders', 'Method': 'GET', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'Dockerfile': 'Dockerfile', 'DockerContext': '/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', 'DockerTag': ''}, inlinecode=None, codesign_config_arn=None, stack_path=''))
2021-05-25 23:06:00,166 | Same function build definition found, adding function (Previous: BuildDefinition(None, /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject, Image, , e326089c-024b-410c-9fe4-d208b1288155, {'Dockerfile': 'Dockerfile', 'DockerContext': '/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', 'DockerTag': ''}, {}, ['Get', 'GetOrders']), Current: BuildDefinition(None, /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject, Image, , 3b6626ec-fedc-4a38-8a4a-efb1496b64b8, {'Dockerfile': 'Dockerfile', 'DockerContext': '/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', 'DockerTag': ''}, {}, []), Function: Function(name='CreateOrder', functionname='CreateOrder', runtime=None, memory=256, timeout=30, handler=None, imageuri='xxx.dkr.ecr.us-east-2.amazonaws.com/yyy', packagetype='Image', imageconfig={'EntryPoint': ['/lambda-entrypoint.sh'], 'Command': ['ExampleAwsProject::Lambdas.Orders.OrderLambdas::CreateOrder']}, codeuri='/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', environment=None, rolearn=None, layers=[], events={'RootGet': {'Type': 'Api', 'Properties': {'Path': '/orders', 'Method': 'POST', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'Dockerfile': 'Dockerfile', 'DockerContext': '/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', 'DockerTag': ''}, inlinecode=None, codesign_config_arn=None, stack_path=''))
2021-05-25 23:06:00,170 | Building codeuri: /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject runtime: None metadata: {'Dockerfile': 'Dockerfile', 'DockerContext': '/mnt/c/Users/SomeUser/Workspace/ExampleAwsProject', 'DockerTag': ''} functions: ['Get', 'GetOrders', 'CreateOrder']
2021-05-25 23:06:00,170 | Building to following folder /mnt/c/Users/SomeUser/Workspace/ExampleAwsProject/.aws-sam/build/Get
2021-05-25 23:06:00,170 | Building image for Get function
2021-05-25 23:06:00,173 | Setting DockerBuildArgs: {} for Get function
2021-05-25 23:06:02,372 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'd44d5af4-75c6-44d5-831d-3ac446e1fda8', 'installationId': 'a6ad6c94-c677-4bd8-aed7-761e980f7253', 'sessionId': 'a3d493b3-1781-4821-bea1-0da6338479de', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.23.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 2348, 'exitReason': 'ConnectionError', 'exitCode': 255}}]}
2021-05-25 23:06:02,738 | Telemetry response: 200
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1071, in _send_output
  File "http/client.py", line 993, in send
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1071, in _send_output
  File "http/client.py", line 993, in send
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 153, in wrapped
  File "samcli/lib/telemetry/metric.py", line 122, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 90, in wrapper
  File "samcli/commands/build/command.py", line 227, in cli
  File "samcli/commands/build/command.py", line 315, in do_cli
  File "samcli/lib/build/app_builder.py", line 169, in build
  File "samcli/lib/build/build_strategy.py", line 41, in build
  File "samcli/lib/build/build_strategy.py", line 52, in _build_functions
  File "samcli/lib/build/build_strategy.py", line 126, in build_single_function_definition
  File "samcli/lib/build/app_builder.py", line 500, in _build_function
  File "samcli/lib/build/app_builder.py", line 343, in _build_lambda_image
  File "docker/api/build.py", line 269, in build
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 226, in _post
  File "requests/sessions.py", line 578, in post
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[21558] Failed to execute script __main__
```

### Expected result:
Expected SAM CLI to build an image of my Lambda functions for testing and deployment.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: 1.15.0
3. AWS region: us-east-2
4. Ubuntu 20.02 running on WSL2
5. Git Bash 2.31.1.windows.1
6. Docker Desktop 3.3.3

**Comment by mgrandis** [comment]
@RockManJoe64 
I see you are using an older version of the CLI (1.15).
Could you update to the latest version and see if the errors persist?

**Comment by mgrandis** [comment]
Yes, we have this issue with the latest 1.24 version https://github.com/aws/aws-sam-cli/issues/2927
Can you try with the 1.23?

**Comment by mgrandis** [comment]
We have released 1.24.1 to address the configparser issue
Can you please try again?
Thanks.

**Comment by mndeveci** [comment]
Hi @RockManJoe64, do you still see the issue with the latest version?

**Comment by wchengru** [comment]
Closed it due to inactive. Please feel free to reopen it if there is any update.

**Comment by stevenlafl** [comment]
Having the same exact problem. Sad to see there's no solution. I downgraded to 1.23 and this does not fix the problem. I have to manually deploy to ECR. 

```
$ sam --version
SAM CLI, version 1.23.0
```

All I'm doing is adding to my function definition:
```
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: stevenlafl/cypress-cucumber-lambda
      DockerContext: .
      Dockerfile: Dockerfile
    Properties:
      Handler: index.handler
      PackageType: Image
```

Connection to... what exactly? I wish it would say. 

```
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1071, in _send_output
  File "http/client.py", line 993, in send
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1071, in _send_output
  File "http/client.py", line 993, in send
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 153, in wrapped
  File "samcli/lib/telemetry/metric.py", line 122, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 90, in wrapper
  File "samcli/commands/build/command.py", line 227, in cli
  File "samcli/commands/build/command.py", line 315, in do_cli
  File "samcli/lib/build/app_builder.py", line 169, in build
  File "samcli/lib/build/build_strategy.py", line 41, in build
  File "samcli/lib/build/build_strategy.py", line 52, in _build_functions
  File "samcli/lib/build/build_strategy.py", line 126, in build_single_function_definition
  File "samcli/lib/build/app_builder.py", line 500, in _build_function
  File "samcli/lib/build/app_builder.py", line 343, in _build_lambda_image
  File "docker/api/build.py", line 269, in build
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 226, in _post
  File "requests/sessions.py", line 578, in post
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[6676] Failed to execute script __main__
```

**Comment by stevenlafl** [comment]
Got it. 
Why specify a `DockerTag` when you have `FROM` in the Dockerfile?

Replacing `DockerTag` with `DockerTag: nodejs14.x.0` works, for anyone wondering.

**Comment by babaMar** [comment]
I'm experiencing this problem with `SAM CLI, version 1.57.0` when building with `PackageType: Image`, here's the command output with `--debug`:

```
2022-09-27 17:19:17,744 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-09-27 17:19:17,744 | Using config file: samconfig.toml, config environment: default
2022-09-27 17:19:17,744 | Expand command line arguments to:
2022-09-27 17:19:17,744 | --template_file=/home/stefano/Repositories/serverless-api-demo/template.yml --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2022-09-27 17:19:17,890 | 'build' command is called
2022-09-27 17:19:17,901 | Collected default values for parameters: {}
2022-09-27 17:19:17,917 | There is no customer defined id or cdk path defined for resource LambdaRole, so we will use the resource logical id as the resource id
2022-09-27 17:19:17,917 | There is no customer defined id or cdk path defined for resource RestApiOnLambda, so we will use the resource logical id as the resource id
2022-09-27 17:19:17,917 | There is no customer defined id or cdk path defined for resource Api, so we will use the resource logical id as the resource id
2022-09-27 17:19:17,919 | 0 stacks found in the template
2022-09-27 17:19:17,919 | Collected default values for parameters: {}
2022-09-27 17:19:17,932 | There is no customer defined id or cdk path defined for resource LambdaRole, so we will use the resource logical id as the resource id
2022-09-27 17:19:17,932 | There is no customer defined id or cdk path defined for resource RestApiOnLambda, so we will use the resource logical id as the resource id
2022-09-27 17:19:17,932 | There is no customer defined id or cdk path defined for resource Api, so we will use the resource logical id as the resource id
2022-09-27 17:19:17,933 | 3 resources found in the stack 
2022-09-27 17:19:17,933 | Found Serverless function with name='RestApiOnLambda' and ImageUri='None'
2022-09-27 17:19:17,933 | --base-dir is not presented, adjusting uri ./ relative to /home/stefano/Repositories/serverless-api-demo/template.yml
2022-09-27 17:19:17,933 | --base-dir is not presented, adjusting uri . relative to /home/stefano/Repositories/serverless-api-demo/template.yml
2022-09-27 17:19:17,944 | 3 resources found in the stack 
2022-09-27 17:19:17,944 | Found Serverless function with name='RestApiOnLambda' and ImageUri='None'
2022-09-27 17:19:17,944 | Instantiating build definitions
2022-09-27 17:19:17,948 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(None, /home/stefano/Repositories/serverless-api-demo, Image, , 2c419f04-8824-40a4-b39c-9ccb50041189, {'DockerTag': 'python:3.8-alpine3.12', 'DockerContext': '/home/stefano/Repositories/serverless-api-demo', 'Dockerfile': 'Dockerfile'}, {}, x86_64, []), Function: Function(function_id='RestApiOnLambda', name='RestApiOnLambda', functionname='RestApiOnLambda', runtime=None, memory=None, timeout=None, handler='app.main.handler', imageuri=None, packagetype='Image', imageconfig=None, codeuri='/home/stefano/Repositories/serverless-api-demo', environment={'Variables': {'DOMAIN_NAME': 'DomainName', 'DATA_TABLE_NAME': 'Music', 'DATA_TABLE_INDEX': 'Artist-Index', 'DATA_TABLE_INDEX_KEY': 'artist', 'DATA_TABLE_ALBUM_ATTRIBUTE': 'album', 'STAGE': 'DeployEnvironment'}}, rolearn='arn:aws:lambda:us-east-1:123456789012:function:LambdaRole', layers=[], events={'ApiEvent': {'Type': 'Api', 'Properties': {'RestApiId': 'Api', 'Path': '/{proxy+}', 'Method': 'ANY'}}}, metadata={'DockerTag': 'python:3.8-alpine3.12', 'DockerContext': '/home/stefano/Repositories/serverless-api-demo', 'Dockerfile': 'Dockerfile', 'SamResourceId': 'RestApiOnLambda'}, inlinecode=None, codesign_config_arn=None, architectures=None, function_url_config=None, stack_path=''))
2022-09-27 17:19:17,949 | Building codeuri: /home/stefano/Repositories/serverless-api-demo runtime: None metadata: {'DockerTag': 'python:3.8-alpine3.12', 'DockerContext': '/home/stefano/Repositories/serverless-api-demo', 'Dockerfile': 'Dockerfile'} architecture: x86_64 functions: RestApiOnLambda
2022-09-27 17:19:17,949 | Building to following folder /home/stefano/Repositories/serverless-api-demo/.aws-sam/build/RestApiOnLambda
2022-09-27 17:19:17,949 | Building image for RestApiOnLambda function
2022-09-27 17:19:17,953 | Setting DockerBuildArgs: {} for RestApiOnLambda function
[1186908] Failed to execute script __main__
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 706, in urlopen
  File "urllib3/connectionpool.py", line 394, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1071, in _send_output
  File "http/client.py", line 993, in send
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 756, in urlopen
  File "urllib3/util/retry.py", line 532, in increment
  File "urllib3/packages/six.py", line 769, in reraise
  File "urllib3/connectionpool.py", line 706, in urlopen
  File "urllib3/connectionpool.py", line 394, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1071, in _send_output
  File "http/client.py", line 993, in send
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 176, in wrapped
  File "samcli/lib/telemetry/metric.py", line 126, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 86, in wrapper
  File "samcli/commands/build/command.py", line 196, in cli
  File "samcli/commands/build/command.py", line 257, in do_cli
  File "samcli/commands/build/build_context.py", line 252, in run
  File "samcli/lib/build/app_builder.py", line 221, in build
  File "samcli/lib/build/build_strategy.py", line 80, in build
  File "samcli/lib/build/build_strategy.py", line 90, in _build_functions
  File "samcli/lib/build/build_strategy.py", line 174, in build_single_function_definition
  File "samcli/lib/build/app_builder.py", line 612, in _build_function
  File "samcli/lib/build/app_builder.py", line 423, in _build_lambda_image
  File "docker/api/build.py", line 269, in build
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 226, in _post
  File "requests/sessions.py", line 590, in post
  File "requests/sessions.py", line 542, in request
  File "requests/sessions.py", line 655, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by babaMar** [comment]
> I'm experiencing this problem with `SAM CLI, version 1.57.0` when building with `PackageType: Image`, here's the command output with `--debug`:
> 
> ```
> 2022-09-27 17:19:17,744 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
> 2022-09-27 17:19:17,744 | Using config file: samconfig.toml, config environment: default
> 2022-09-27 17:19:17,744 | Expand command line arguments to:
> 2022-09-27 17:19:17,744 | --template_file=/home/stefano/Repositories/serverless-api-demo/template.yml --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
> 2022-09-27 17:19:17,890 | 'build' command is called
> 2022-09-27 17:19:17,901 | Collected default values for parameters: {}
> 2022-09-27 17:19:17,917 | There is no customer defined id or cdk path defined for resource LambdaRole, so we will use the resource logical id as the resource id
> 2022-09-27 17:19:17,917 | There is no customer defined id or cdk path defined for resource RestApiOnLambda, so we will use the resource logical id as the resource id
> 2022-09-27 17:19:17,917 | There is no customer defined id or cdk path defined for resource Api, so we will use the resource logical id as the resource id
> 2022-09-27 17:19:17,919 | 0 stacks found in the template
> 2022-09-27 17:19:17,919 | Collected default values for parameters: {}
> 2022-09-27 17:19:17,932 | There is no customer defined id or cdk path defined for resource LambdaRole, so we will use the resource logical id as the resource id
> 2022-09-27 17:19:17,932 | There is no customer defined id or cdk path defined for resource RestApiOnLambda, so we will use the resource logical id as the resource id
> 2022-09-27 17:19:17,932 | There is no customer defined id or cdk path defined for resource Api, so we will use the resource logical id as the resource id
> 2022-09-27 17:19:17,933 | 3 resources found in the stack 
> 2022-09-27 17:19:17,933 | Found Serverless function with name='RestApiOnLambda' and ImageUri='None'
> 2022-09-27 17:19:17,933 | --base-dir is not presented, adjusting uri ./ relative to /home/stefano/Repositories/serverless-api-demo/template.yml
> 2022-09-27 17:19:17,933 | --base-dir is not presented, adjusting uri . relative to /home/stefano/Repositories/serverless-api-demo/template.yml
> 2022-09-27 17:19:17,944 | 3 resources found in the stack 
> 2022-09-27 17:19:17,944 | Found Serverless function with name='RestApiOnLambda' and ImageUri='None'
> 2022-09-27 17:19:17,944 | Instantiating build definitions
> 2022-09-27 17:19:17,948 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(None, /home/stefano/Repositories/serverless-api-demo, Image, , 2c419f04-8824-40a4-b39c-9ccb50041189, {'DockerTag': 'python:3.8-alpine3.12', 'DockerContext': '/home/stefano/Repositories/serverless-api-demo', 'Dockerfile': 'Dockerfile'}, {}, x86_64, []), Function: Function(function_id='RestApiOnLambda', name='RestApiOnLambda', functionname='RestApiOnLambda', runtime=None, memory=None, timeout=None, handler='app.main.handler', imageuri=None, packagetype='Image', imageconfig=None, codeuri='/home/stefano/Repositories/serverless-api-demo', environment={'Variables': {'DOMAIN_NAME': 'DomainName', 'DATA_TABLE_NAME': 'Music', 'DATA_TABLE_INDEX': 'Artist-Index', 'DATA_TABLE_INDEX_KEY': 'artist', 'DATA_TABLE_ALBUM_ATTRIBUTE': 'album', 'STAGE': 'DeployEnvironment'}}, rolearn='arn:aws:lambda:us-east-1:123456789012:function:LambdaRole', layers=[], events={'ApiEvent': {'Type': 'Api', 'Properties': {'RestApiId': 'Api', 'Path': '/{proxy+}', 'Method': 'ANY'}}}, metadata={'DockerTag': 'python:3.8-alpine3.12', 'DockerContext': '/home/stefano/Repositories/serverless-api-demo', 'Dockerfile': 'Dockerfile', 'SamResourceId': 'RestApiOnLambda'}, inlinecode=None, codesign_config_arn=None, architectures=None, function_url_config=None, stack_path=''))
> 2022-09-27 17:19:17,949 | Building codeuri: /home/stefano/Repositories/serverless-api-demo runtime: None metadata: {'DockerTag': 'python:3.8-alpine3.12', 'DockerContext': '/home/stefano/Repositories/serverless-api-demo', 'Dockerfile': 'Dockerfile'} architecture: x86_64 functions: RestApiOnLambda
> 2022-09-27 17:19:17,949 | Building to following folder /home/stefano/Repositories/serverless-api-demo/.aws-sam/build/RestApiOnLambda
> 2022-09-27 17:19:17,949 | Building image for RestApiOnLambda function
> 2022-09-27 17:19:17,953 | Setting DockerBuildArgs: {} for RestApiOnLambda function
> [1186908] Failed to execute script __main__
> Traceback (most recent call last):
>   File "urllib3/connectionpool.py", line 706, in urlopen
>   File "urllib3/connectionpool.py", line 394, in _make_request
>   File "http/client.py", line 1277, in request
>   File "http/client.py", line 1323, in _send_request
>   File "http/client.py", line 1272, in endheaders
>   File "http/client.py", line 1071, in _send_output
>   File "http/client.py", line 993, in send
> ConnectionResetError: [Errno 104] Connection reset by peer
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "requests/adapters.py", line 449, in send
>   File "urllib3/connectionpool.py", line 756, in urlopen
>   File "urllib3/util/retry.py", line 532, in increment
>   File "urllib3/packages/six.py", line 769, in reraise
>   File "urllib3/connectionpool.py", line 706, in urlopen
>   File "urllib3/connectionpool.py", line 394, in _make_request
>   File "http/client.py", line 1277, in request
>   File "http/client.py", line 1323, in _send_request
>   File "http/client.py", line 1272, in endheaders
>   File "http/client.py", line 1071, in _send_output
>   File "http/client.py", line 993, in send
> urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "samcli/__main__.py", line 12, in <module>
>   File "click/core.py", line 829, in __call__
>   File "click/core.py", line 782, in main
>   File "click/core.py", line 1259, in invoke
>   File "click/core.py", line 1066, in invoke
>   File "click/core.py", line 610, in invoke
>   File "click/decorators.py", line 73, in new_func
>   File "click/core.py", line 610, in invoke
>   File "samcli/lib/telemetry/metric.py", line 176, in wrapped
>   File "samcli/lib/telemetry/metric.py", line 126, in wrapped
>   File "samcli/lib/utils/version_checker.py", line 41, in wrapped
>   File "samcli/cli/main.py", line 86, in wrapper
>   File "samcli/commands/build/command.py", line 196, in cli
>   File "samcli/commands/build/command.py", line 257, in do_cli
>   File "samcli/commands/build/build_context.py", line 252, in run
>   File "samcli/lib/build/app_builder.py", line 221, in build
>   File "samcli/lib/build/build_strategy.py", line 80, in build
>   File "samcli/lib/build/build_strategy.py", line 90, in _build_functions
>   File "samcli/lib/build/build_strategy.py", line 174, in build_single_function_definition
>   File "samcli/lib/build/app_builder.py", line 612, in _build_function
>   File "samcli/lib/build/app_builder.py", line 423, in _build_lambda_image
>   File "docker/api/build.py", line 269, in build
>   File "docker/utils/decorators.py", line 46, in inner
>   File "docker/api/client.py", line 226, in _post
>   File "requests/sessions.py", line 590, in post
>   File "requests/sessions.py", line 542, in request
>   File "requests/sessions.py", line 655, in send
>   File "requests/adapters.py", line 498, in send
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> ```
> 
> the `template.yml`:
> 
> ```
>   RestApiOnLambda:
>     Type: AWS::Serverless::Function
>     Properties:
>       PackageType: Image
>       Events:
>         ApiEvent:
>           Type: Api
>           Properties:
>             RestApiId: !Ref Api
>             Path: /{proxy+}
>             Method: ANY
>       Role: !GetAtt LambdaRole.Arn
>       Environment:
>         Variables:
>           DOMAIN_NAME: !Ref DomainName
>           DATA_TABLE_NAME: 'Music'
>           DATA_TABLE_INDEX: 'Artist-Index'
>           DATA_TABLE_INDEX_KEY: 'artist'
>           DATA_TABLE_ALBUM_ATTRIBUTE: 'album'
>           STAGE: !Ref DeployEnvironment
>     Metadata:
>       DockerTag: python:3.8-alpine3.12
>       DockerContext: ./
>       Dockerfile: Dockerfile
> ```

OK I think I understand, when using a custom `Dockerfile` there's no need to specify `DockerTag`, it tries to pull something that doesn't exists if the tag is not in `public.ecr.aws/lambda`. I removed the `DockerTag` field from `Metadata` and it is building now.

**Comment by Thomas-McKanna** [comment]
In case it helps someone, I was receiving this same error because my disk was full.

**Comment by grinay** [comment]
@Thomas-McKanna oh, man , thanks, You saved my day!
