### ISSUE TITLE
Bug: Error on sam build command

### ISSUE THREAD

**Issue by getanwar** [aws/aws-sam-cli#4527]
### Description:

I can not build projects after upgrading sam cli from 1.65.0 to 1.67.0
After facing the issue for a couple of times I thought it might fix if I remove python3.8 manually and reinstall aws-sam-cli. But it did not solve it. I confirmed that python3.8 was reinstall with aws-sam-cli

### Steps to reproduce:

1. run `brew upgrade aws-sam-cli`
2. try to build any sam project 

I encountered the following error after doing that.

### Observed result:

`sam build --debug`
```Traceback (most recent call last):
  File "/opt/homebrew/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/samcli/cli/command.py", line 133, in get_command
    mod = importlib.import_module(pkg_name)
  File "/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/samcli/commands/build/__init__.py", line 6, in <module>
    from .command import cli  # noqa
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 12, in <module>
    from samcli.commands._utils.options import (
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/samcli/commands/_utils/options.py", line 21, in <module>
    from samcli.commands._utils.template import get_template_data, TemplateNotFoundException
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/samcli/commands/_utils/template.py", line 10, in <module>
    from botocore.utils import set_value_from_jmespath
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/botocore/utils.py", line 37, in <module>
    import botocore.httpsession
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.crypto
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3268, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 12.4 (Monterey)
4. `sam --version`: SAM CLI, version 1.67.0
5. AWS region: us-east-2

`Add --debug flag to command you are running`

**Comment by JoL0712** [comment]
cryptography 39.0.0 no longer supports openssl 1.1.0 or older and thus is causing this issue. 
Reference: 
- https://github.com/pyca/cryptography/issues/7959
- https://cryptography.io/en/latest/changelog/#v39-0-0

aws-sam-cli uses the latest cryptography while using pyopenssl 22.0.0. These two are incompatible.
You can probably workaround this for now by installing cryptography 38.0.4 until the dependencies are fixed.

**Comment by nszeitli** [comment]
Getting this in all our github actions using aws-actions/setup-sam. New years day dependency bomb!

**Comment by getanwar** [comment]
> cryptography 39.0.0 no longer supports openssl 1.1.0 or older and thus is causing this issue. Reference:
> 
> * [AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms' pyca/cryptography#7959](https://github.com/pyca/cryptography/issues/7959)
> * https://cryptography.io/en/latest/changelog/#v39-0-0
> 
> aws-sam-cli uses the latest cryptography while using pyopenssl 22.0.0. These two are incompatible. As a workaround until the dependencies are fixed, you can force install cryptography 38.0.4 and sam should work (I just verified with my CI/CD builds which all got broken today due to the cryptography update).

Thank you so much. I got it work!

**Comment by reaperhulk** [comment]
`pyOpenSSL` declares a lower and upper bound on its own dependencies to avoid this sort of issue, however it didn't start to do so until version `22.1.0`. This repository currently pins `22.0.0` (https://github.com/aws/aws-sam-cli/blob/07fa5f478dfa04c45521af188b39fbaff622cc72/requirements/base.txt#L21). Once the pin is updated you won't see this type of issue again in the future.

**Comment by Obrecsys** [comment]
> 

How did you get it to work?

**Comment by karimdaghari** [comment]
> cryptography 39.0.0 no longer supports openssl 1.1.0 or older and thus is causing this issue.
Reference:
>
> https://github.com/pyca/cryptography/issues/7959
> https://cryptography.io/en/latest/changelog/#v39-0-0
aws-sam-cli uses the latest cryptography while using pyopenssl 22.0.0. These two are incompatible.
> As a workaround until the dependencies are fixed, you can force install cryptography 38.0.4 and sam should work (I just verified with my CI/CD builds which all got broken today due to the cryptography update).

If you're on MacOS/Homebrew here's how to implement the workaround:
```
/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/bin/pip install --force-reinstall "cryptography==38.0.4"
```

**Comment by korostelevm** [comment]
Having this issue in codebuild as well (aws/codebuild/standard:5.0)

**Comment by altaurog** [comment]
@nszeitli for aws-actions/setup-sam, you can add the following step to github workflow (worked for us):
```
      - name: sam fix https://github.com/aws/aws-sam-cli/issues/4527
        run: $(dirname $(readlink $(which sam)))/pip install --force-reinstall "cryptography==38.0.4"
```

**Comment by moelasmar** [comment]
We are checking this issue. Could you please confirm do you see this issue only on homebrew installation or also on the pkg installation?

**Comment by aahung** [comment]
Error using [setup-sam GH action](https://github.com/aws-actions/setup-sam) (with `pip install` inside)

https://github.com/aahung/test-pipeline-20211006/actions/runs/3825152161/jobs/6507908315

**Comment by moelasmar** [comment]
This issue is only affecting the people who use `pip` to install `AWS SAM CLI`, or use the homebrew installation way on `ARM architecture (linux or mac)`. 

For macOS users, We recommend using the PKG installation approach, and For Linux users, we recommend the Command line installer way. You can find all the installation details [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html#install-sam-cli-instructions).
 
For `pip` installations, you can try the @karimdaghari workaround (Thanks @karimdaghari for your help :) )

We are working on the fix for this issue, we will update this issue once it got released.

**Comment by moelasmar** [comment]
Thanks @getanwar for raising this issue. Could you please try the PKG installation and let us know if it fixed your issue?

**Comment by gaurav7700** [comment]
> karimdaghari

Thanks, it worked !

**Comment by fizwan** [comment]
as of now, github actions that depends on sam cli still failed

**Comment by Raul-CC** [comment]
> ons that depends on sam cli still failed

Kudos to @altaurog, his line of the fixed version of cryptography worked like a charm:
This is our current setup:
`      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v1
        with:
          version: 1.65.0
      - name: sam fix https://github.com/aws/aws-sam-cli/issues/4527
        run: $(dirname $(readlink $(which sam)))/pip install --force-reinstall "cryptography==38.0.4"`

**Comment by altaurog** [comment]
Thanks @Raul-CC !  As an aside, note that the [latest version of aws-actions/setup-sam is v2](https://github.com/aws-actions/setup-sam/tags).  (Sorry this isn’t exactly on-topic)

**Comment by shearn89** [comment]
> Thanks @Raul-CC ! As an aside, note that the [latest version of aws-actions/setup-sam is v2](https://github.com/aws-actions/setup-sam/tags). (Sorry, I realize this isn’t exactly on-topic)

Is v2 still affected by this bug? If not, hooray for updates!

**Comment by sadeghipour** [comment]
We have same situation since yesterday on Gitlab / Docker on image python:3.8.

**Comment by altaurog** [comment]
@shearn89 I believe v2 is still affected.

**Comment by DiegoVictor** [comment]
For `github-actions`, another solution is set a version:
```
- uses: aws-actions/setup-sam@v2
  with:
     version: 1.37.0
```

**Comment by ozzyca** [comment]
> 
This version worked for me, though version 1.65.0 still fails.

**Comment by ugocottin** [comment]
You can go up to version 1.59.0

**Comment by mackinnonlyle** [comment]
I am very new to github/it in general. construction worker, just working on completing cloud-resume-challenge and a few days ago I had my tests working fine and github actions and workflows working fine. made a commit today and it fails! I wasnt sure what was going on. The fix listed here worked for me!  

- uses: aws-actions/setup-sam@v2
  with:
     version: 1.59.0

**Comment by hawflau** [comment]
Closing as the fix has been released with AWS SAM CLI v1.68.0 - https://github.com/aws/aws-sam-cli/releases/tag/v1.68.0

**Comment by Gordonbaes** [comment]
Hi guys, help! 

I am having the same problem with my CI/CD pipelines on Google Cloud. I tried to reinstall cryptography but doesn't seem to work - it keeps returning the same AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'. 

Not sure if my syntax below is correct?

pip install --force-reinstall "cryptography==38.0.4"
pip3 install --force-reinstall "cryptography==38.0.4"

I also tried to include cryptography==38.0.4 in my requirements.txt file and reinstall it, only to receive the same error:

![image](https://user-images.githubusercontent.com/122841256/212782945-142ec496-d26f-454c-8926-7a0517807a25.png)

**Comment by altaurog** [comment]
Check `which pip` you are using @Gordonbaes .  If it isn’t `/home/htrinh/.local/bin/pip` it won’t help you.

**Comment by Gordonbaes** [comment]
> Check `which pip` you are using @Gordonbaes . If it isn’t `/home/htrinh/.local/bin/pip` it won’t help you.
Thanks @altaurog I was looking at the wrong place. However when I tried to run `pip install --force-reinstall "cryptography==38.0.4"` in `/usr/local/bin/pip` it didn't work either...
The error is still AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'.

Below is a screenshot of the beginning of the error:
![image](https://user-images.githubusercontent.com/122841256/213037518-92bfa378-2c47-4979-b479-74ff76e454f9.png)


Apologies if my question sounds silly, I'm super new on this :)

**Comment by altaurog** [comment]
@Gordonbaes it is difficult to diagnose this without more information, but it doesn’t look like the same error as reported here.  This error arose when invoking `sam`, and v1.68.0 is meant to fix that.  Your error arises when invoking `pip`, which would seem to indicate the python env is somehow broken.  What version of `pip` do you have?
